singleton pattern
syg4806/CSWIKI_Data pull request #18
Opened 2021-04-14 11:32 UTC by leejungmin05

https://github.com/syg4806/CSWIKI_Data/issues/17

2021-04-14 14:09 UTC, syg4806 requested changes
구글링통해서 내용을 정리한것이라면, 레퍼런스도 꼭 추가해주세요!

2021-04-14 14:09 UTC, syg4806 commented on singletonPattern.md
> +
you can answer 추가해주세용

2021-04-14 14:09 UTC, syg4806 commented on singletonPattern.md
> +2) lazy init (인스턴스 요청할 때 생성됨)
2. 을 의도하신 것 같아용

2021-04-14 15:08 UTC, leejungmin05 commented
수정하고 내용 추가했습니다

2021-04-16 07:17 UTC, syg4806 requested changes
마크다운 작성하시고 어떻게 보여지는지도 한번 꼭 확인해주세요.
변경한내용 빌드해서 테스트해보는 것과 같은 맥락입니다!

2021-04-16 07:17 UTC, syg4806 commented on singletonPattern.md
> +#싱글턴 패턴 (Singleton Pattern)
# 뒤에 공백넣어주세요

2021-04-16 07:17 UTC, syg4806 commented on singletonPattern.md
> +##싱글턴 패턴이란?
[dito]

2021-04-16 14:38 UTC, closed without merging

2021-04-16 14:45 UTC, leejungmin05 commented
#23