Design pattern/singleton
syg4806/CSWIKI_Data pull request #23
Opened 2021-04-16 14:43 UTC by leejungmin05

2021-04-16 14:46 UTC, syg4806 commented on singletonPattern.md
> +###4) 다른 언어에서의 구현
ㅎㅎ plz

2021-04-16 14:47 UTC, syg4806 requested changes
plz, check the file looks correct before you push!

2021-04-16 15:22 UTC, leejungmin05 commented on singletonPattern.md
> +###4) 다른 언어에서의 구현
웁스 sorry ..

2021-04-16 15:25 UTC, leejungmin05 commented on singletonPattern.md
> +###4) 다른 언어에서의 구현
근데 마크다운 저기 띄어쓰고 안쓰고 차이가 있는가요?? 저는 preview로 봐도 차이가 없는데 ...!

2021-04-17 13:15 UTC, syg4806 commented on singletonPattern.md
> +###4) 다른 언어에서의 구현
## 뒤에 공백이 있어야지 헤더 속성이 적용됩니다!

2021-04-17 13:16 UTC, syg4806 commented
LGTM

2021-04-17 13:16 UTC, syg4806 approved these changes

2021-04-17 13:16 UTC, merged