Greedy Approach 중 MST에 관해, 그리고 MST의 구현 과정의 하나인 Prim's algorithm에 대해 작…
syg4806/CSWIKI_Data pull request #27
Opened 2021-04-18 12:11 UTC by yuncheol-AHN

…성, 추후 Greedy Approach에 관한 알고리즘 추가하겠습니다.

2021-04-19 09:03 UTC, syg4806 commented
pr 이름이랑 description도 신경써주세요!

2021-04-19 09:06 UTC, syg4806 commented on Algorithm/Greedy_Approach/MST/MST.md
> +
you can answer 추가해주세요!
https://github.com/syg4806/CSWIKI_Data/blob/main/template.md 참고

2021-04-19 09:06 UTC, syg4806 commented on Algorithm/Greedy_Approach/MST/MST.md
> +- Kruskal's Algorithm
reference추가해주세용

2021-04-19 09:06 UTC, syg4806 commented on Algorithm/Greedy_Approach/Prim_algorithm/Prim_algorithm.md
> +
dito

2021-04-19 09:06 UTC, syg4806 commented on Algorithm/Greedy_Approach/Prim_algorithm/Prim_algorithm.md
> +  - 시간 복잡도 : (n - 1) * (n - 1) ∈ O(n&#178;)
dito

2021-04-19 09:06 UTC, syg4806 commented on Algorithm/Greedy_Approach/MST/MST.md
> +![Test](./image1.png)
png첨부가 안된 것 같아요

2021-04-19 09:06 UTC, syg4806 requested changes
확인해주세요

2021-04-27 04:13 UTC, yuncheol-AHN commented
> pr 이름이랑 description도 신경써주세요!

네~ 윤권넴

2021-04-27 04:14 UTC, yuncheol-AHN commented on Algorithm/Greedy_Approach/MST/MST.md
> +
참고할게요^_^

2021-04-27 04:15 UTC, yuncheol-AHN commented on Algorithm/Greedy_Approach/MST/MST.md
> +- Kruskal's Algorithm
네~

2021-04-27 04:20 UTC, yuncheol-AHN commented on Algorithm/Greedy_Approach/Prim_algorithm/Prim_algorithm.md
> +
dito!

2021-04-27 04:20 UTC, yuncheol-AHN commented on Algorithm/Greedy_Approach/Prim_algorithm/Prim_algorithm.md
> +  - 시간 복잡도 : (n - 1) * (n - 1) ∈ O(n&#178;)
dito!

2021-04-29 08:26 UTC, syg4806 requested changes

2021-04-29 08:26 UTC, syg4806 commented on Algorithm/MST.md
> +Reference
reference없으면 그냥 지워주세요

2021-04-29 08:26 UTC, syg4806 commented on Algorithm/Prim_algorithm.md
> +- X
[dito]

2021-04-29 08:26 UTC, syg4806 commented on Algorithm/Prim_algorithm.md
> +```
이 부분 원하는 모양대로 출력이 안되는 것 같습니다 아마 \``` 를 넣어서 인듯하네요

2021-04-29 08:26 UTC, syg4806 commented on Algorithm/Greedy_Approach/Prim_algorithm/Prim_algorithm.md
> +  - 시간 복잡도 : (n - 1) * (n - 1) ∈ O(n&#178;)
check againg plz

2021-04-30 13:16 UTC, yuncheol-AHN commented on Algorithm/MST.md
> +Reference
확인했습니다!

2021-04-30 13:16 UTC, yuncheol-AHN commented on Algorithm/Prim_algorithm.md
> +- X
확인했습니다!

2021-04-30 13:17 UTC, yuncheol-AHN commented on Algorithm/Prim_algorithm.md
> +```
확인했습니다!

2021-05-01 00:16 UTC, syg4806 approved these changes
LGTM

2021-05-01 02:31 UTC, merged