add Stack.md
syg4806/CSWIKI_Data pull request #36
Opened 2021-04-25 12:56 UTC by rkdmf1026

자료구조에서 스택부분 추가했습니다.

2021-04-25 14:19 UTC, syg4806 requested changes

2021-04-25 14:19 UTC, syg4806 commented on DataStructure/Stack.md
> +하지만 단점으로는 배열과 달리 한번에 원하는 데이터의 접근이 불가능하다.
이 부분 출력이 원하는 바가 아닌 것 같습니다! 확인해주세용

2021-04-25 14:19 UTC, syg4806 commented on DataStructure/Stack.md
> +```
\``` 옆에 어떤 언어인지 적으면 언어에 맞게 코드에 색이 입혀집니다!
ex)
 \```java
코드
\```

2021-04-25 16:26 UTC, rkdmf1026 commented on DataStructure/Stack.md
> +```
좋은 정보 감사합니다 ㅎㅎ

2021-04-26 00:46 UTC, syg4806 approved these changes
LGTM

2021-04-26 06:57 UTC, merged