Note what is datastructure
syg4806/CSWIKI_Data pull request #9
Opened 2021-04-13 06:12 UTC by rkdmf1026

DataStructure 폴더 생성
What Is DataStructure.md 파일 생성

2021-04-13 09:35 UTC, syg4806 commented on DataStructure/What is DataStructure.md
> +
마크다운으로 출력했을때 어떻게 보이는지 확인해보세용
원하는 모양이 아닌것같습니다!

2021-04-14 00:57 UTC, rkdmf1026 commented on DataStructure/What is DataStructure.md
> +
마크다운 형식으로 고치고, 맞춤법 수정했습니다.
그런데 수정할 때 이런식으로 커밋하는게 맞나요??

2021-04-14 01:34 UTC, syg4806 requested changes

2021-04-14 01:34 UTC, syg4806 commented on DataStructure/What is DataStructure.md
> +# # # Data Structure란?
?? 이건 맞았는디

2021-04-14 01:34 UTC, syg4806 commented on DataStructure/What is DataStructure.md
> +- 배열(Array) : 가장 일반적인 구조로 인덱스와 인덱스에 대응하는 데이터들로 이루어진 자료구조
얘는 왜 앞에 띄어쓰기 4개없나요

2021-04-14 01:34 UTC, syg4806 commented on DataStructure/What is DataStructure.md
> +2. 추상화
[nit]
1. a
1. b
1. c
```
1. a
1. b 
1. c
```
으로 해도 넘버링 됩니당

2021-04-14 01:34 UTC, syg4806 commented on DataStructure/What is DataStructure.md
> +
넵 맞아용

2021-04-15 01:02 UTC, rkdmf1026 commented on DataStructure/What is DataStructure.md
> +# # # Data Structure란?
에디터에서 옮기다가 실수했습니다.
나머지 수정쳐하고 다시 커밋했습니다.

2021-04-15 16:15 UTC, paulkim1997 commented on DataStructure/What is DataStructure.md
> +## Reference
잘 보고 갑니다!

2021-04-16 07:09 UTC, comeheredart commented on DataStructure/What is DataStructure.md
> +## Reference
다음편 빨리주세요!

2021-04-16 07:14 UTC, syg4806 approved these changes

2021-04-16 07:15 UTC, merged